### ISSUE TITLE
Bugs in code

### ISSUE THREAD

**Issue by meera-raghav** [Klarrio/open-stream-processing-benchmark#6] opened 2023-11-08 13:18 UTC
I am trying to run this for local deployment with my windows machine, I tried all the steps mentioned in the local deployment, i installed the docker containers with Kafka and zookeeper
![osp](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/a8fc86ec-8651-4676-9dc4-32ac140781a0)

I am able to compile the benchmark when i run it with sbt compile but i am facing java run time issue when i am giving sbt run. I am not sure there is bug in the code which I am unable to figure it out. Please help me with the error . I have added the error message. I also tried it with WSL still i get the same error.

WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by sbt.TrapExit$ (file:/C:/Users/HP/.sbt/boot/scala-2.10.7/org.scala-sbt/sbt/0.13.18/run-0.13.18.jar)
WARNING: Please consider reporting this to the maintainers of sbt.TrapExit$
WARNING: System::setSecurityManager will be removed in a future release
[info] Loading project definition from E:\benchmark\open-stream-processing-benchmark\benchmark\project\project
[info] Loading project definition from E:\benchmark\open-stream-processing-benchmark\benchmark\project
[info] Set current project to stream-benchmark (in build file:/E:/benchmark/open-stream-processing-benchmark/benchmark/)
java.lang.RuntimeException: No main class detected.
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last benchmark/compile:run for the full output.
[error] (benchmark/compile:run) No main class detected.
[error] Total time: 0 s, completed 08-Nov-2023, 2:10:13 pm
![error](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/63fcd50b-1431-4638-bf0b-5f9ce9bd47d8)

**Comment by gvdongen** [comment] 2023-11-08 22:10
Hi! Thanks for trying it out! For which framework are you trying to run the benchmark?

**Comment by meera-raghav** [comment] 2023-11-09 07:51
Hi,

I am running with docker with kafka and zookeeper and I trying to run for the common benchmark on my local machine if I understand your question correctly and I am not using AWS for this.

**Comment by gvdongen** [comment] 2023-11-09 07:56
The common module is just some utilities that all the benchmarks share so you can't run it separately. You need to either run the flink-benchmark, kafka-benchmark or one of the others. So I think that's why you get the error that there is no main detected.

**Comment by meera-raghav** [comment] 2023-11-09 08:05
Hi,

Ok, as you suggested i tried with the specific flink-benchmark but still i get the same error. I have attached the screenshot

![image](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/30771e70-5578-406e-b817-d95fa00dd514)

**Comment by gvdongen** [comment] 2023-11-09 09:14
You are trying to run the benchmark from the test folder. I think you need to run from `benchmark/flink-benchmark`.
I don't have time to try it out now and it has been some time since I last run this but it seems that the issue is not with the code but with the location you are running the command from. It does not know which main class it needs to run.

**Comment by meera-raghav** [comment] 2023-11-09 09:25
Hi,

I tried running from the benchmark/flink-benchmark/src path still i face the same error where the main files are present. I have attached the screenshot. I want to know whether this is an issue which configuration or something else which i am missing?

![image](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/d1718f64-42c9-4f89-9dd5-7d806ce06f7a)

**Comment by meera-raghav** [comment] 2023-11-09 12:40
Hello,


Thats ok not a problem, if you could help me out with ideas to rectify the error its a great help . As you suggested if i run in the specific benchmark for example `benchmark/flink-benchmark` , i still get error and I think the error is obvious because here there is no build.sbt file or project. I have attached the screenshot for it. 

I think I am making mistake in running the files or there is missing instructions. Could you help me on that??

![image](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/a767aa17-8678-40e1-aedc-4a99943c04dc)

**Comment by gvdongen** [comment] 2023-11-09 21:00
Does this work for you? Go to the root of the folder (where the `build.sbt`) file is and execute there:
`sbt "project flink-benchmark" run`
Make sure you set the environment variables:
```
MODE=constant-rate;
DEPLOYMENT_TYPE=local;
KAFKA_BOOTSTRAP_SERVERS=$(hostname -I | head -n1 | awk '{print $1\;}'):9092;
ZOOKEEPER_SERVER=$(hostname -I | head -n1 | awk '{print $1\;}'):2181
```

**Comment by meera-raghav** [comment] 2023-11-13 15:28
Hi Giselle,

1) it works me in WSL for flink and kafka frameworks but for spark benchmark I am again facing an error. I have attached screenshot. Can you check and let me know whats the error?

![image](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/ddb2db53-a20a-406b-8771-e6b64b8dd8a5)


2) Also, for flink and kafka benchmarks when i run the data stream generator in parellel while running benchmarks i see these values zeros does the ingestion even happening?

![image](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/a85218ba-d469-4c8d-961f-bdf03db20ba7)

**Comment by meera-raghav** [comment] 2023-11-24 09:04
Hi,

Can you kindly help me with this?

**Comment by gvdongen** [comment] 2023-11-28 21:26
Looks like the problem for spark has to do with the sbt dependencies being tagged as "provided". You need to do this only if it runs on a cluster. If you run with intellij you can set a flag to include the dependencies that are set as provided.

**Comment by gvdongen** [comment] 2023-11-28 21:26
For the ingesting of data, please add some logs to see if it can find the file.

**Comment by meera-raghav** [comment] 2023-11-29 21:55
Hi,

I have cross checked , There is no problem finding the filepath but there is problem in reading the filepath i think. I have given the correct path of the file. it is able to find the path of the file as you can see the comments here reading the file "will read file from local resources" also i asked for the path, it is the path where my WSL ubuntu runs and my data is located. It is also able to read how many inputs which is one file so one " 20:31:09.863 [pool-22-thread-3] INFO  o.a.hadoop.mapred.FileInputFormat - Total input paths to process : 1 ". The problem here is  from here from line number 32 https://github.com/Klarrio/open-stream-processing-benchmark/blob/master/data-stream-generator/src/main/scala/ingest/ConstantRatePublisher.scala from this function the code doesn't work. It doesn't give any explicit error also, so its hard to locate what problem in reading the file.
```
 val fileOrderedDF = rawFile.map { observation =>
 val (keyLine, observationLine) = DataUtils.splitLineI

nKeyAndValue(observation)
 val timestampOfObservation = DataUtils.extractTimestamp(observation)
```
I have attached the logs for this while giving `sbt run`
[mylogs.txt](https://github.com/Klarrio/open-stream-processing-benchmark/files/13540019/mylogs.txt)
I have attached the screenshot also. Kindly help me out. Thanks in Advance 
![image](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/b26f8a16-fc7d-40f4-b20e-7e08ed5d135e)

**Comment by gvdongen** [comment] 2024-01-04 07:33
The original value for localPath in the config file was
`local.path = "./src/main/resources/data/time*/*"`

Did you make any changes to the data files or to this value?
The only thing I can come up with is that it doesn't find the file... But hard to debug from a distance. The original code works for me...

**Comment by meera-raghav** [comment] 2024-01-04 15:34
Hello,

Thanks for the reply it worked for me, the problem was it has a problem reading from resources.conf file so i had to give the path of the files again in environment variables. 
I am having a generic doubt now, when i use spark cluster is it necessary to  submit jobs for both data stream generator and benchmark? If i submit jobs for both of them i am facing error due to version issues

**Comment by gvdongen** [comment] 2024-01-04 15:50
Okay! 

I think I always ran the data stream generator as a normal Docker container. You can spin up multiple to have larger throughput.

**Comment by meera-raghav** [comment] 2024-01-05 07:52
Thank you ! Also I have one more generic doubt, so these are the metrics i get in my kafka console when i run the output consumer directory. I have attached screenshot as well for your reference. Here i can see the p50,p75,p99.... these are latency values and is the count throughtput value? (Number of messages per second) ??

![Screenshot from 2023-12-13 17-51-32](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/d32682c2-1c5a-4acb-90eb-45268de969c7)

```
11:22:14.489 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=3240, min=300, max=1305, mean=795.9557175088679, stddev=279.615649145168, p50=792.0, p75=1044.0, p95=1230.0, p98=1257.0, p99=1268.0, p999=1303.0
11:22:24.481 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=6840, min=300, max=1307, mean=798.4493201603766, stddev=277.60735005327524, p50=792.0, p75=1036.0, p95=1232.0, p98=1261.0, p99=1279.0, p999=1307.0
11:22:34.481 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=10440, min=306, max=1307, mean=793.8214233770394, stddev=281.01384677905054, p50=780.0, p75=1040.0, p95=1223.0, p98=1257.0, p99=1270.0, p999=1305.0
11:22:44.480 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=14040, min=290, max=1307, mean=793.7541288511204, stddev=286.5287873138549, p50=782.0, p75=1053.0, p95=1231.0, p98=1264.0, p99=1276.0, p999=1301.0
11:22:54.480 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=17640, min=294, max=1307, mean=798.1770958845639, stddev=286.9437337635272, p50=788.0, p75=1062.0, p95=1232.0, p98=1261.0, p99=1273.0, p999=1301.0
11:23:04.480 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=21240, min=294, max=1310, mean=798.2146608895195, stddev=281.365900567859, p50=789.0, p75=1061.0, p95=1231.0, p98=1258.0, p99=1276.0, p999=1310.0
11:23:14.481 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=24840, min=294, max=1310, mean=793.8801815401504, stddev=281.0337832843953, p50=788.0, p75=1048.0, p95=1234.0, p98=1255.0, p99=1273.0, p999=1310.0
11:23:24.480 [metrics-logger-reporter-1-thread-1] INFO  output.consumer.LocalModeWriter$ - type=HISTOGRAM, name=flink_ie420321c-8bcf-454e-8383-6c30beeeb923_e3_v1_b100_s1_l2_t1702548447760, count=28440, min=294, max=1310, mean=796.2567707141538, stddev=279.32856703872125, p50=791.0, p75=1048.0, p95=1231.0, p98=1258.0, p99=1279.0, p999=1307.0
```

**Comment by meera-raghav** [comment] 2024-01-17 14:33
Hi

Could you kindly answer my doubts? I will be very happy. Thank you

**Comment by meera-raghav** [comment] 2024-02-10 11:43
HI,

Can i kindly have an update here?

**Comment by meera-raghav** [comment] 2024-03-01 15:27
HI,

Even after spinning up multiple data generator the throughput value is very standard its not increasing . Can you please help me how to increase the throughput?

**Comment by gvdongen** [comment] 2024-03-01 15:40
`the throughput value is very standard` --> What do you mean? If you spin up two data generator containers, you don't see twice the number of messages on Kafka?

**Comment by meera-raghav** [comment] 2024-03-01 16:00
NO i dont see, In the output of input throughput and output throughput i only see a standard number 360. I have attached the screenshot also 
![Screenshot from 2024-03-01 16-59-38](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/b3901765-c4c2-4581-97e6-6746167becfb)
I see the same value for input throughput and output throughput

**Comment by gvdongen** [comment] 2024-03-01 16:21
Did you correctly set the environment variable PUBLISHER_NB to the number of data stream generators you have running?
https://github.com/Klarrio/open-stream-processing-benchmark/blob/8839de8101f3ac5338c02dc5dcfdd57c7aeec612/data-stream-generator/src/main/resources/resources.conf#L11

**Comment by meera-raghav** [comment] 2024-03-08 17:20
Ahh got it thanks! Also I have a generic doubt how do i get a sustainable throughput here by running constant-rate? that only gives latency values and not sustainable throughput

**Comment by meera-raghav** [comment] 2024-04-11 06:18
HI,
![Screenshot from 2024-04-11 08-08-14](https://github.com/Klarrio/open-stream-processing-benchmark/assets/106863494/775eb4f8-3979-4925-8a08-13de6ee327a3)


I have a generic doubt on kafka cluster to perform experiments on vertical scaling I am facing this issue in the benchmark. Should i change anything it for it to support vertical scaling in the benchmark configuration? Can you please help me debug this issue?

**Comment by gvdongen** [comment] 2024-04-11 10:23
I can't really understand the context from this screenshot. But this issue seems to be more of a Kafka-related question/issue, so I would suggest to ask/search in the Kafka documentation/forums. 
Also, for GitHub issues, you would file an issue per bug. Since the original question was answered, I will close this issue. You can file a new issue if you encounter a benchmark-related bug. 
I hope you can find a solution soon! Thank you for trying out the benchmark.

**Comment by meera-raghav** [comment] 2024-04-16 08:13
thanks

**Closed as completed** 2024-04-16 08:12 UTC
